### ISSUE TITLE
Provide a doc for installing the Morphling UI

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/morphling#18]

**Comment by lwangbm** [comment]
There is a readme.md file regarding detailed UI design/develop: https://github.com/alibaba/morphling/blob/main/console/README.md
Additional fixes: 
1.  add a deployment guide at root readme.md, in commit https://github.com/kubedl-io/morphling/commit/6c0e05b04283f33c521c9f78cdee22f06c4a09c4 
2. add a ui doc at website, in commit https://github.com/kubedl-io/website/commit/9fea1414c0c9541412a2d34dc50c72f144febc96
