### ISSUE TITLE
create a helm chart

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/morphling#3]
create a helm chart.
also see the 'make helm-chart' in kubedl repo

**Comment by lwangbm** [comment]
created helm chart in commit (https://github.com/kubedl-io/morphling/commit/e8ceb26cdcbf4c5d699d3649e222d3919a9e753c)

**Comment by lwangbm** [comment]
handled in (https://github.com/kubedl-io/morphling/commit/e8ceb26cdcbf4c5d699d3649e222d3919a9e753c), will close this issue
