### ISSUE TITLE
[BUG]morphling not install in morphling-system will raise error for  ConfigMap "morphling-data-config" not found

### ISSUE THREAD

**Issue by shikanon** [kubedl-io/morphling#34]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I install morphling not in the default namespace - morphling-system, and I open the page for pe-submit, it raise the error for ConfigMap "morphling-data-config" not found. But In the new namespace, which morphling installed, that has the configmap.

**What did you expect to happen:**

It can run in any namespace install.

**Anything else we need to know?**:

**Environment:**
- Morphling version: master branch
- Kubernetes version (use `kubectl version`): v1.19

**Comment by shikanon** [comment]
error info:
```bash
E0819 02:05:44.089065       1 common.go:11] failed to marshal common config, err: failed to get morphling-data-config, err: ConfigMap "morphling-data-config" not found
```

**Comment by lwangbm** [comment]
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> 
> When I install morphling not in the default namespace - morphling-system, and I open the page for pe-submit, it raise the error for ConfigMap "morphling-data-config" not found. But In the new namespace, which morphling installed, that has the configmap.
> 
> **What did you expect to happen:**
> 
> It can run in any namespace install.
> 
> **Anything else we need to know?**:
> 
> **Environment:**
> 
> * Morphling version: master branch
> * Kubernetes version (use `kubectl version`): v1.19

Thanks for reaching out. Currently, our design requires installing morphling in `morphling-system` namespace. This helps in coordinating all the behaviors of components, i.e., installation, communication, uninstallation, etc. 
We may enable installing morphling in arbitrary namespaces. 
BTW, may I know the necessity to not install it in `morphling-system` namespace in your environment? This will help us assess the priority of further upgrades.

**Comment by shikanon** [comment]
@lwangbm I find the DefaultNameSpace write is code and can not by set parameter for user, It is not friendly for namespace management

**Comment by shikanon** [comment]
@lwangbm It can provide a environment variable for user, if people not use can use the default parameter.

**Comment by lwangbm** [comment]
> @lwangbm It can provide a environment variable for user, if people not use can use the default parameter.

Thank you for the comments and suggestions. These help a lot. We will enable the user-defined namespace shortly and will keep you updated.

**Comment by lwangbm** [comment]
> @lwangbm It can provide a environment variable for user, if people not use can use the default parameter.

Fixed in https://github.com/kubedl-io/morphling/commit/47a5221ae0037cf1c844593cbd2bce3cbb2c0cb3.
Helm-chart can be used when installing Morphling in arbitrary namespaces by running
`helm install morphling ./helm/morphling --create-namespace -n test-namespace`

@shikanon  Thanks again

**Comment by shikanon** [comment]
@lwangbm nice!
