### ISSUE TITLE
支持的GPU虚拟化方案

### ISSUE THREAD

**Issue by bug-developer021** [kubedl-io/morphling#43]
如果需要对GPU请求参数进行调优
1. 是否需要部署GPU虚拟化组件
2. 是否只支持阿里的cGPU

**Comment by lwangbm** [comment]
Thank you for reaching out.

1. Yes, if the hyper-parameters you are tuning include fine-grained GPU shares like GPU memory size or duty cycle sharing, you need to install your own GPU sharing tools on hosts first.

2. Morphling does not reply on any underlying vGPU frameworks. You may use cGPU, vGPU, MPS, .etc.

Hopes these may find your questions well.
