### ISSUE TITLE
Failed to get ready for the component for morphling

### ISSUE THREAD

**Issue by czq693497091** [kubedl-io/morphling#44]
After execute ”kubectl create namespace morphling-system”

kubectl apply -k manifests/configmap
kubectl apply -k manifests/controllers
kubectl apply -k manifests/pv
kubectl apply -k manifests/mysql-db
kubectl apply -k manifests/db-manager
kubectl apply -k manifests/ui
kubectl apply -k manifests/algorithm

root@xxx# kubectl get deployment -n morphling-system
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
morphling-algorithm-server   0/1     1            0           26m
morphling-controller         0/1     1            0           28m
morphling-db-manager         0/1     1            0           28m
morphling-mysql              0/1     1            0           28m
morphling-ui                 0/1     1            0           28m

I have installed all docker images for the components but fail to start and can access to the website of morphling

**Comment by lwangbm** [comment]
> After execute ”kubectl create namespace morphling-system”
> 
> kubectl apply -k manifests/configmap kubectl apply -k manifests/controllers kubectl apply -k manifests/pv kubectl apply -k manifests/mysql-db kubectl apply -k manifests/db-manager kubectl apply -k manifests/ui kubectl apply -k manifests/algorithm
> 
> root@xxx# kubectl get deployment -n morphling-system NAME READY UP-TO-DATE AVAILABLE AGE morphling-algorithm-server 0/1 1 0 26m morphling-controller 0/1 1 0 28m morphling-db-manager 0/1 1 0 28m morphling-mysql 0/1 1 0 28m morphling-ui 0/1 1 0 28m
> 
> I have installed all docker images for the components but fail to start and can access to the website of morphling

Thank you for reaching out.

It seems that your deployments are not ready yet: AVAILABLE is 0/1.

Can you check the event of pods, providing more detailed info, so that we can inspect this problm

**Comment by lwangbm** [comment]
will close this issue
